name: player
description: Three D Radio live and on demand
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audio_service: ^0.17.0-nullsafety.0
  cached_network_image: ^3.0.0-nullsafety
  dio: ^4.0.0-prev3
  firebase_analytics: ^7.1.1
  flutter_html: ^2.0.0-nullsafety.0
  flutter_redux: ^0.8.2
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  hive: ^2.0.0
  html_unescape: ^2.0.0
  json_annotation: ^4.0.1
  just_audio: ^0.7.3
  package_info: ^2.0.0
  provider: ^5.0.0
  redux: ^5.0.0
  redux_dev_tools: ^0.7.0
  redux_entity: ^1.0.3
  redux_epics: ^0.15.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  redux_remote_devtools: ^3.0.0
  rxdart: ^0.26.0
  sentry: ^4.1.0-nullsafety.1
  timezone: ^0.7.0-nullsafety.0
  url_launcher: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  intl_utils: ^2.1.0
  json_serializable: ^4.1.0
  mockito: ^5.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
