name: player
description: Three D Radio live and on demand
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audio_service: ^0.16.1
  cached_network_image: ^2.3.1
  dio: ^3.0.10
  firebase_analytics: ^6.2.0
  flutter_html: ^1.0.0
  flutter_redux: ^0.6.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.0
  hive: ^1.4.4
  html_unescape: ^1.0.1+3
  intl: ^0.17.0-nullsafety.2
  json_annotation: ^3.0.1
  just_audio: ^0.6.5
  package_info: ^0.4.3+4
  provider: ^4.3.2+2
  redux: ^4.0.0+3
  redux_dev_tools: ^0.5.2
  redux_entity: ^0.2.0
  redux_epics: ^0.14.0
  redux_persist: ^0.8.4
  redux_persist_flutter: ^0.8.3
  redux_remote_devtools: ^2.0.0
  rxdart: ^0.24.1
  sentry: ">=3.0.0 <4.0.0"
  timezone: ^0.5.7
  url_launcher: ^5.7.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  analyzer: ^0.40.6
  intl: ^0.17.0-nullsafety.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  intl_utils: ^1.9.0
  json_serializable: ^3.4.1
  junitreport: ^1.3.1
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
